name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake ffamato app
        run: |
          curl -s -o /dev/null https://ffamato.streamlit.app || exit 0
